# -*- coding: utf-8 -*-
leetcode_path = '../../src/leetcode/'
problem_path = '../../src/leetcode/problem/'
config_path = '../../src/.vuepress/sidebar.ts'
solution_path = '../../src/leetcode/solution/'
solotion_list_path = '../../src/leetcode/outline/solution_list.md'
plan_list_path = '../../src/leetcode/outline/plan/'
tag_list_path = '../../src/leetcode/outline/tag/'
tag_list_readme = '../../src/leetcode/outline/tag/README.md'
tag_absolute_path = '/leetcode/outline/tag/'
categories_path = '../origins/categories_list.md'
origin_path = '../origins/'

tags_zh_to_en = {
    '数组': 'array',
    '矩阵': 'matrix',
    '链表': 'linked-list',
    '双向链表': 'doubly-linked-list',
    '栈': 'stack',
    '单调栈': 'monotonic-stack',
    '队列': 'queue',
    '单调队列': 'monotonic-queue',
    '堆（优先队列）': 'heap-priority-queue',
    '哈希表': 'hash-table',
    '字符串': 'string',
    '字符串匹配': 'string-matching',
    '树': 'tree',
    '二叉树': 'binary-tree',
    '二叉搜索树': 'binary-search-tree',
    '最小生成树': 'minimum-spanning-tree',
    '图': 'graph',
    '有序集合': 'ordered-set',
    '拓扑排序': 'topological-sort',
    '最短路': 'shortest-path',
    '强连通分量': 'strongly-connected-components',
    '欧拉回路': 'eulerian-circuit',
    '双连通分量': 'biconnected-components',
    '并查集': 'disjoint-set-union',
    '字典树': 'trie',
    '线段树': 'segment-tree',
    '树状数组': 'fenwick-tree',
    '后缀数组': 'suffix-array',
    '枚举': 'enumeration',
    '递归': 'recursion',
    '分治': 'divide-and-conquer',
    '回溯': 'backtracking',
    '贪心': 'greedy',
    '动态规划': 'dynamic-programming',
    '排序': 'sorting',
    '桶排序': 'bucket-sort',
    '计数排序': 'counting-sort',
    '基数排序': 'radix-sort',
    '归并排序': 'merge-sort',
    '快速选择': 'quick-select',
    '二分查找': 'binary-search',
    '记忆化搜索': 'memoization',
    '深度优先搜索': 'depth-first-search',
    '广度优先搜索': 'breadth-first-search',
    '双指针': 'two-pointers',
    '位运算': 'bit-manipulation',
    '前缀和': 'prefix-sum',
    '计数': 'counting',
    '滑动窗口': 'sliding-window',
    '状态压缩': 'state-compression',
    '哈希函数': 'hash-function',
    '滚动哈希': 'rolling-hash',
    '扫描线': 'sweep-line',
    '数学': 'mathematics',
    '数论': 'number-theory',
    '几何': 'geometry',
    '博弈': 'game-theory',
    '模拟': 'simulation',
    '组合数学': 'combinatorics',
    '随机化': 'randomized-algorithms',
    '概率与统计': 'probability-and-statistics',
    '水塘抽样': 'reservoir-sampling',
    '拒绝采样': 'rejection-sampling',
    '数据库': 'database',
    '设计': 'design',
    '数据流': 'data-streams',
    '脑筋急转弯': 'brain-teasers',
    '交互': 'interaction',
    '迭代器': 'iterators',
    '多线程': 'multithreading',
}
