# -*- coding: utf-8 -*-
online_path = 'https://wangfuyou.com/leetcode-js'
origin_path = '../origins/'
categories_path = '../origins/categories_list.md'

base_path = '../../src/'
problem_path = base_path + 'problem/'
interview_path = base_path + 'interview/'
offer_path = base_path + 'offer/'
offer2_path = base_path + 'offer2/'
plan_list_path = base_path + 'plan/'
tag_list_path = base_path + 'tag/'

problem_readme = base_path + 'problem/README.md'
interview_readme = base_path + 'interview/README.md'
offer_readme = base_path + 'offer/README.md'
offer2_readme = base_path + 'offer2/README.md'
tag_list_readme = base_path + 'tag/README.md'

config_path = base_path + '.vuepress/sidebar.ts'

offer_dict = {
    "shu-zu-zhong-zhong-fu-de-shu-zi-lcof": "3,jz_offer_03_1,数组中重复的数字",
    "er-wei-shu-zu-zhong-de-cha-zhao-lcof": "4,jz_offer_04_1,二维数组中的查找",
    "ti-huan-kong-ge-lcof": "5,jz_offer_05_1,替换空格",
    "cong-wei-dao-tou-da-yin-lian-biao-lcof": "6,jz_offer_06_1,从尾到头打印链表",
    "zhong-jian-er-cha-shu-lcof": "7,jz_offer_07_1,重建二叉树",
    "yong-liang-ge-zhan-shi-xian-dui-lie-lcof": "9,jz_offer_09_1,用两个栈实现队列",
    "fei-bo-na-qi-shu-lie-lcof": "10,jz_offer_10_1,斐波那契数列",
    "qing-wa-tiao-tai-jie-wen-ti-lcof": "10-II,jz_offer_10_2,青蛙跳台阶问题",
    "xuan-zhuan-shu-zu-de-zui-xiao-shu-zi-lcof": "11,jz_offer_11_1,旋转数组的最小数字",
    "ju-zhen-zhong-de-lu-jing-lcof": "12,jz_offer_12_1,矩阵中的路径",
    "ji-qi-ren-de-yun-dong-fan-wei-lcof": "13,jz_offer_13_1,机器人的运动范围",
    "jian-sheng-zi-lcof": "14,jz_offer_14_1,剪绳子",
    "jian-sheng-zi-ii-lcof": "14-II,jz_offer_14_2,剪绳子 II",
    "er-jin-zhi-zhong-1de-ge-shu-lcof": "15,jz_offer_15_1,二进制中1的个数",
    "shu-zhi-de-zheng-shu-ci-fang-lcof": "16,jz_offer_16_1,数值的整数次方",
    "da-yin-cong-1dao-zui-da-de-nwei-shu-lcof": "17,jz_offer_17_1,打印从1到最大的n位数",
    "shan-chu-lian-biao-de-jie-dian-lcof": "18,jz_offer_18_1,删除链表的节点",
    "zheng-ze-biao-da-shi-pi-pei-lcof": "19,jz_offer_19_1,正则表达式匹配",
    "biao-shi-shu-zhi-de-zi-fu-chuan-lcof": "20,jz_offer_20_1,表示数值的字符串",
    "diao-zheng-shu-zu-shun-xu-shi-qi-shu-wei-yu-ou-shu-qian-mian-lcof": "21,jz_offer_21_1,调整数组顺序使奇数位于偶数前面",
    "lian-biao-zhong-dao-shu-di-kge-jie-dian-lcof": "22,jz_offer_22_1,链表中倒数第k个节点",
    "fan-zhuan-lian-biao-lcof": "24,jz_offer_24_1,反转链表",
    "he-bing-liang-ge-pai-xu-de-lian-biao-lcof": "25,jz_offer_25_1,合并两个排序的链表",
    "shu-de-zi-jie-gou-lcof": "26,jz_offer_26_1,树的子结构",
    "er-cha-shu-de-jing-xiang-lcof": "27,jz_offer_27_1,二叉树的镜像",
    "dui-cheng-de-er-cha-shu-lcof": "28,jz_offer_28_1,对称的二叉树",
    "shun-shi-zhen-da-yin-ju-zhen-lcof": "29,jz_offer_29_1,顺时针打印矩阵",
    "bao-han-minhan-shu-de-zhan-lcof": "30,jz_offer_30_1,包含min函数的栈",
    "zhan-de-ya-ru-dan-chu-xu-lie-lcof": "31,jz_offer_31_1,栈的压入、弹出序列",
    "cong-shang-dao-xia-da-yin-er-cha-shu-lcof": "32,jz_offer_32_1,从上到下打印二叉树",
    "cong-shang-dao-xia-da-yin-er-cha-shu-ii-lcof": "32-II,jz_offer_32_2,从上到下打印二叉树 II",
    "cong-shang-dao-xia-da-yin-er-cha-shu-iii-lcof": "32-III,jz_offer_32_3,从上到下打印二叉树 III",
    "er-cha-sou-suo-shu-de-hou-xu-bian-li-xu-lie-lcof": "33,jz_offer_33_1,二叉搜索树的后序遍历序列",
    "er-cha-shu-zhong-he-wei-mou-yi-zhi-de-lu-jing-lcof": "34,jz_offer_34_1,二叉树中和为某一值的路径",
    "fu-za-lian-biao-de-fu-zhi-lcof": "35,jz_offer_35_1,复杂链表的复制",
    "er-cha-sou-suo-shu-yu-shuang-xiang-lian-biao-lcof": "36,jz_offer_36_1,二叉搜索树与双向链表",
    "xu-lie-hua-er-cha-shu-lcof": "37,jz_offer_37_1,序列化二叉树",
    "zi-fu-chuan-de-pai-lie-lcof": "38,jz_offer_38_1,字符串的排列",
    "shu-zu-zhong-chu-xian-ci-shu-chao-guo-yi-ban-de-shu-zi-lcof": "39,jz_offer_39_1,数组中出现次数超过一半的数字",
    "zui-xiao-de-kge-shu-lcof": "40,jz_offer_40_1,最小的k个数",
    "shu-ju-liu-zhong-de-zhong-wei-shu-lcof": "41,jz_offer_41_1,数据流中的中位数",
    "lian-xu-zi-shu-zu-de-zui-da-he-lcof": "42,jz_offer_42_1,连续子数组的最大和",
    "1nzheng-shu-zhong-1chu-xian-de-ci-shu-lcof": "43,jz_offer_43_1,1～n 整数中 1 出现的次数",
    "shu-zi-xu-lie-zhong-mou-yi-wei-de-shu-zi-lcof": "44,jz_offer_44_1,数字序列中某一位的数字",
    "ba-shu-zu-pai-cheng-zui-xiao-de-shu-lcof": "45,jz_offer_45_1,把数组排成最小的数",
    "ba-shu-zi-fan-yi-cheng-zi-fu-chuan-lcof": "46,jz_offer_46_1,把数字翻译成字符串",
    "li-wu-de-zui-da-jie-zhi-lcof": "47,jz_offer_47_1,礼物的最大价值",
    "zui-chang-bu-han-zhong-fu-zi-fu-de-zi-zi-fu-chuan-lcof": "48,jz_offer_48_1,最长不含重复字符的子字符串",
    "chou-shu-lcof": "49,jz_offer_49_1,丑数",
    "di-yi-ge-zhi-chu-xian-yi-ci-de-zi-fu-lcof": "50,jz_offer_50_1,第一个只出现一次的字符",
    "shu-zu-zhong-de-ni-xu-dui-lcof": "51,jz_offer_51_1,数组中的逆序对",
    "liang-ge-lian-biao-de-di-yi-ge-gong-gong-jie-dian-lcof": "52,jz_offer_52_1,两个链表的第一个公共节点",
    "zai-pai-xu-shu-zu-zhong-cha-zhao-shu-zi-lcof": "53,jz_offer_53_1,在排序数组中查找数字 I",
    "que-shi-de-shu-zi-lcof": "53-II,jz_offer_53_2,0～n-1中缺失的数字",
    "er-cha-sou-suo-shu-de-di-kda-jie-dian-lcof": "54,jz_offer_54_1,二叉搜索树的第k大节点",
    "er-cha-shu-de-shen-du-lcof": "55,jz_offer_55_1,二叉树的深度",
    "ping-heng-er-cha-shu-lcof": "55-II,jz_offer_55_2,平衡二叉树",
    "shu-zu-zhong-shu-zi-chu-xian-de-ci-shu-lcof": "56,jz_offer_56_1,数组中数字出现的次数",
    "shu-zu-zhong-shu-zi-chu-xian-de-ci-shu-ii-lcof": "56-II,jz_offer_56_2,数组中数字出现的次数 II",
    "he-wei-sde-liang-ge-shu-zi-lcof": "57,jz_offer_57_1,和为s的两个数字",
    "he-wei-sde-lian-xu-zheng-shu-xu-lie-lcof": "57-II,jz_offer_57_2,和为s的连续正数序列",
    "fan-zhuan-dan-ci-shun-xu-lcof": "58,jz_offer_58_1,翻转单词顺序",
    "zuo-xuan-zhuan-zi-fu-chuan-lcof": "58-II,jz_offer_58_2,左旋转字符串",
    "hua-dong-chuang-kou-de-zui-da-zhi-lcof": "59,jz_offer_59_1,滑动窗口的最大值",
    "dui-lie-de-zui-da-zhi-lcof": "59-II,jz_offer_59_2,队列的最大值",
    "nge-tou-zi-de-dian-shu-lcof": "60,jz_offer_60_1,n个骰子的点数",
    "bu-ke-pai-zhong-de-shun-zi-lcof": "61,jz_offer_61_1,扑克牌中的顺子",
    "yuan-quan-zhong-zui-hou-sheng-xia-de-shu-zi-lcof": "62,jz_offer_62_1,圆圈中最后剩下的数字",
    "gu-piao-de-zui-da-li-run-lcof": "63,jz_offer_63_1,股票的最大利润",
    "qiu-12n-lcof": "64,jz_offer_64_1,求1+2+…+n",
    "bu-yong-jia-jian-cheng-chu-zuo-jia-fa-lcof": "65,jz_offer_65_1,不用加减乘除做加法",
    "gou-jian-cheng-ji-shu-zu-lcof": "66,jz_offer_66_1,构建乘积数组",
    "ba-zi-fu-chuan-zhuan-huan-cheng-zheng-shu-lcof": "67,jz_offer_67_1,把字符串转换成整数",
    "er-cha-sou-suo-shu-de-zui-jin-gong-gong-zu-xian-lcof": "68,jz_offer_68_1,二叉搜索树的最近公共祖先",
    "er-cha-shu-de-zui-jin-gong-gong-zu-xian-lcof": "68-II,jz_offer_68_2,二叉树的最近公共祖先"
}

offer2_dict = {
    "xoh6Oh": "1,jz_offer_II_001,整数除法",
    "JFETK5": "2,jz_offer_II_002,二进制加法",
    "w3tCBm": "3,jz_offer_II_003,前 n 个数字二进制中 1 的个数",
    "WGki4K": "4,jz_offer_II_004,只出现一次的数字",
    "aseY1I": "5,jz_offer_II_005,单词长度的最大乘积",
    "kLl5u1": "6,jz_offer_II_006,排序数组中两个数字之和",
    "1fGaJU": "7,jz_offer_II_007,数组中和为 0 的三个数",
    "2VG8Kg": "8,jz_offer_II_008,和大于等于 target 的最短子数组",
    "ZVAVXX": "9,jz_offer_II_009,乘积小于 K 的子数组",
    "QTMn0o": "10,jz_offer_II_010,和为 k 的子数组",
    "A1NYOS": "11,jz_offer_II_011,0 和 1 个数相同的子数组",
    "tvdfij": "12,jz_offer_II_012,左右两边子数组的和相等",
    "O4NDxx": "13,jz_offer_II_013,二维子矩阵的和",
    "MPnaiL": "14,jz_offer_II_014,字符串中的变位词",
    "VabMRr": "15,jz_offer_II_015,字符串中的所有变位词",
    "wtcaE1": "16,jz_offer_II_016,不含重复字符的最长子字符串",
    "M1oyTv": "17,jz_offer_II_017,含有所有字符的最短字符串",
    "XltzEq": "18,jz_offer_II_018,有效的回文",
    "RQku0D": "19,jz_offer_II_019,最多删除一个字符得到回文",
    "a7VOhD": "20,jz_offer_II_020,回文子字符串的个数",
    "SLwz0R": "21,jz_offer_II_021,删除链表的倒数第 n 个结点",
    "c32eOV": "22,jz_offer_II_022,链表中环的入口节点",
    "3u1WK4": "23,jz_offer_II_023,两个链表的第一个重合节点",
    "UHnkqh": "24,jz_offer_II_024,反转链表",
    "lMSNwu": "25,jz_offer_II_025,链表中的两数相加",
    "LGjMqU": "26,jz_offer_II_026,重排链表",
    "aMhZSa": "27,jz_offer_II_027,回文链表",
    "Qv1Da2": "28,jz_offer_II_028,展平多级双向链表",
    "4ueAj6": "29,jz_offer_II_029,排序的循环链表",
    "FortPu": "30,jz_offer_II_030,插入、删除和随机访问都是 O(1) 的容器",
    "OrIXps": "31,jz_offer_II_031,最近最少使用缓存",
    "dKk3P7": "32,jz_offer_II_032,有效的变位词",
    "sfvd7V": "33,jz_offer_II_033,变位词组",
    "lwyVBB": "34,jz_offer_II_034,外星语言是否排序",
    "569nqc": "35,jz_offer_II_035,最小时间差",
    "8Zf90G": "36,jz_offer_II_036,后缀表达式",
    "XagZNi": "37,jz_offer_II_037,小行星碰撞",
    "iIQa4I": "38,jz_offer_II_038,每日温度",
    "0ynMMM": "39,jz_offer_II_039,直方图最大矩形面积",
    "PLYXKQ": "40,jz_offer_II_040,矩阵中最大的矩形",
    "qIsx9U": "41,jz_offer_II_041,滑动窗口的平均值",
    "H8086Q": "42,jz_offer_II_042,最近请求次数",
    "NaqhDT": "43,jz_offer_II_043,往完全二叉树添加节点",
    "hPov7L": "44,jz_offer_II_044,二叉树每层的最大值",
    "LwUNpT": "45,jz_offer_II_045,二叉树最底层最左边的值",
    "WNC0Lk": "46,jz_offer_II_046,二叉树的右侧视图",
    "pOCWxh": "47,jz_offer_II_047,二叉树剪枝",
    "h54YBf": "48,jz_offer_II_048,序列化与反序列化二叉树",
    "3Etpl5": "49,jz_offer_II_049,从根节点到叶节点的路径数字之和",
    "6eUYwP": "50,jz_offer_II_050,向下的路径节点之和",
    "jC7MId": "51,jz_offer_II_051,节点之和最大的路径",
    "NYBBNL": "52,jz_offer_II_052,展平二叉搜索树",
    "P5rCT8": "53,jz_offer_II_053,二叉搜索树中的中序后继",
    "w6cpku": "54,jz_offer_II_054,所有大于等于节点的值之和",
    "kTOapQ": "55,jz_offer_II_055,二叉搜索树迭代器",
    "opLdQZ": "56,jz_offer_II_056,二叉搜索树中两个节点之和",
    "7WqeDu": "57,jz_offer_II_057,值和下标之差都在给定的范围内",
    "fi9suh": "58,jz_offer_II_058,日程表",
    "jBjn9C": "59,jz_offer_II_059,数据流的第 K 大数值",
    "g5c51o": "60,jz_offer_II_060,出现频率最高的 k 个数字",
    "qn8gGX": "61,jz_offer_II_061,和最小的 k 个数对",
    "QC3q1f": "62,jz_offer_II_062,实现前缀树",
    "UhWRSj": "63,jz_offer_II_063,替换单词",
    "US1pGT": "64,jz_offer_II_064,神奇的字典",
    "iSwD2y": "65,jz_offer_II_065,最短的单词编码",
    "z1R5dt": "66,jz_offer_II_066,单词之和",
    "ms70jA": "67,jz_offer_II_067,最大的异或",
    "N6YdxV": "68,jz_offer_II_068,查找插入位置",
    "B1IidL": "69,jz_offer_II_069,山峰数组的顶部",
    "skFtm2": "70,jz_offer_II_070,排序数组中只出现一次的数字",
    "cuyjEf": "71,jz_offer_II_071,按权重生成随机数",
    "jJ0w9p": "72,jz_offer_II_072,求平方根",
    "nZZqjQ": "73,jz_offer_II_073,狒狒吃香蕉",
    "SsGoHC": "74,jz_offer_II_074,合并区间",
    "0H97ZC": "75,jz_offer_II_075,数组相对排序",
    "xx4gT2": "76,jz_offer_II_076,数组中的第 k 大的数字",
    "7WHec2": "77,jz_offer_II_077,链表排序",
    "vvXgSW": "78,jz_offer_II_078,合并排序链表",
    "TVdhkn": "79,jz_offer_II_079,所有子集",
    "uUsW3B": "80,jz_offer_II_080,含有 k 个元素的组合",
    "Ygoe9J": "81,jz_offer_II_081,允许重复选择元素的组合",
    "4sjJUc": "82,jz_offer_II_082,含有重复元素集合的组合",
    "VvJkup": "83,jz_offer_II_083,没有重复元素集合的全排列",
    "7p8L0Z": "84,jz_offer_II_084,含有重复元素集合的全排列",
    "IDBivT": "85,jz_offer_II_085,生成匹配的括号",
    "M99OJA": "86,jz_offer_II_086,分割回文子字符串",
    "0on3uN": "87,jz_offer_II_087,复原 IP",
    "GzCJIP": "88,jz_offer_II_088,爬楼梯的最少成本",
    "Gu0c2T": "89,jz_offer_II_089,房屋偷盗",
    "PzWKhm": "90,jz_offer_II_090,环形房屋偷盗",
    "JEj789": "91,jz_offer_II_091,粉刷房子",
    "cyJERH": "92,jz_offer_II_092,翻转字符",
    "Q91FMA": "93,jz_offer_II_093,最长斐波那契数列",
    "omKAoA": "94,jz_offer_II_094,最少回文分割",
    "qJnOS7": "95,jz_offer_II_095,最长公共子序列",
    "IY6buf": "96,jz_offer_II_096,字符串交织",
    "21dk04": "97,jz_offer_II_097,子序列的数目",
    "2AoeFn": "98,jz_offer_II_098,路径的数目",
    "0i0mDW": "99,jz_offer_II_099,最小路径之和",
    "IlPe0q": "100,jz_offer_II_100,三角形中最小路径之和",
    "NUPfPr": "101,jz_offer_II_101,分割等和子集",
    "YaVDxD": "102,jz_offer_II_102,加减的目标值",
    "gaM7Ch": "103,jz_offer_II_103,最少的硬币数目",
    "D0F0SV": "104,jz_offer_II_104,排列的数目",
    "ZL6zAn": "105,jz_offer_II_105,岛屿的最大面积",
    "vEAB3K": "106,jz_offer_II_106,二分图",
    "2bCMpM": "107,jz_offer_II_107,矩阵中的距离",
    "om3reC": "108,jz_offer_II_108,单词演变",
    "zlDJc7": "109,jz_offer_II_109,开密码锁",
    "bP4bmD": "110,jz_offer_II_110,所有路径",
    "vlzXQL": "111,jz_offer_II_111,计算除法",
    "fpTFWP": "112,jz_offer_II_112,最长递增路径",
    "QA2IGt": "113,jz_offer_II_113,课程顺序",
    "Jf1JuT": "114,jz_offer_II_114,外星文字典",
    "ur2n8P": "115,jz_offer_II_115,重建序列",
    "bLyHh0": "116,jz_offer_II_116,省份数量",
    "H6lPxb": "117,jz_offer_II_117,相似的字符串",
    "7LpjUW": "118,jz_offer_II_118,多余的边",
    "WhsWhI": "119,jz_offer_II_119,最长连续序列",
}